services:
  - type: web
    name: titrari-ro
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        value: https://titrari.scara.ovh # schimbă cu URL-ul tău real
    healthCheckPath: /health
    autoDeploy: true

